import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "@/assets/styles/index.scss";
import { Theme } from "@radix-ui/themes";
import ReduxProvider from './redux-provider';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <h1>Root Layout</h1>
//         {children}
//       </body>
//     </html>
//   );
// }




export default function RootLayout({ children }: Readonly<{children: React.ReactNode}>) {
  return (
    <ReduxProvider>
      <html suppressHydrationWarning>
        <head>
          {/* <link rel="preload" href="/_next/static/css/30a0450f062b33f4.css" as="style"> */}
        </head>
        <body>
          <Theme>{children}</Theme>
        </body>
      </html>
    </ReduxProvider>
  )
}